### ISSUE TITLE
Display custom items in DeluxeMenus

### ISSUE THREAD

**Issue by RomaGreat55** [knokko/custom-items-gradle#143]
Hello! How can i display custom items from your plugin in DeluxeMenus or ChestCommands?

**Comment by knokko** [comment]
I *think* DeluxeMenus can display custom items using its NBT feature: https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/item#nbt-tags-custommodeldata

If it supports nested NBT tags, you should be able to use something like `KnokkosCustomItems: Name: editor_item_name` in `nbt_string`. If it doesn't support nested keys, you can add simpler `NBT` to your custom items via the Editor and use that.

I *think* ChestCommands can also display custom items by using `NBT-DATA: {KnokkosCustomItems:{Name:"editor_item_name"}}`. See https://filoghost.me/docs/chest-commands/attributes.

**Comment by RomaGreat55** [comment]
It works. Thank you a lot!
