### ISSUE TITLE
Custom Block Spawning

### ISSUE THREAD

**Issue by BobtheBob123456** [knokko/custom-items-gradle#158]
Basically, rather then using the set block command, we can use the editor to specify where the block spawns naturally. We could change the y level in which the block spawns, the biome, and how many spawn in a certain area.

It would be much better than using the set block command every time we need to place a block.

Thanks

**Comment by knokko** [comment]
You are basically describing 2 issues here:
(1) Using custom blocks in world generation
(2) An easier way to place blocks

Issue (1) will be a rather complex task and I will keep this one for a while. Regarding (2), there is an easier way to place custom blocks: you can create a custom *item* for the block. Using that item, you can place the block just like you can place regular blocks.
