### ISSUE TITLE
Bedrock Issues

### ISSUE THREAD

**Issue by BobtheBob123456** [knokko/custom-items-gradle#182]
Hello,
I am contacting you guys because the bedrock inventory glitch (When trying to move items from slot to slot it glitches out and doesn't work making it impossible to craft)is still present.

 This time it only affects players who play on Pockest Edition (PE). Could these issues please be fixed?

Thanks,

**Comment by knokko** [comment]
Are these the same issues as described in #160 ?
Does it occur only for custom items? Or vanilla items as well?
And is it solved for non-PE bedrock players?

**Comment by BobtheBob123456** [comment]
Yes, it is the same issues. It occurs for all items, custom or not, and only affects PE players

**Comment by knokko** [comment]
I will try to dig up my PE account (hoping it's still valid) when I have some more time.

**Comment by BobtheBob123456** [comment]
Thanks you so much for fixing this

**Comment by knokko** [comment]
I hope these are fixed in KCI 13, but I don't have pocket edition, so...
