### ISSUE TITLE
Is there a more efficient way to edit other than the editor?

### ISSUE THREAD

**Issue by HansOffice** [knokko/custom-items-gradle#192]
The nature of opening and closing and importing materials one at a time and then importing items is too inefficient, have you considered developing a more efficient way of editing? For example, batch editing or a way to directly write out the item materials and corresponding item properties

**Comment by knokko** [comment]
You can use the `Load all textures in a folder` button to speed up the texture loading. Other than that, I have no clue how you would want to speed it up: you will need to define the names and attributes of the items one way or another. (Besides, creating the textures is usually most of the work.)

**Comment by HansOffice** [comment]
Like the MythicMobs type of item editing, you can directly write the item properties and materials, so it may be more efficient to do so

**Comment by knokko** [comment]
In that case, you still need to write the item properties (manually). The only difference is that you do it in a text editor rather than the Editor. Why would that be significantly faster?

**Comment by HansOffice** [comment]
Using a text editor, you can copy a part of the code and then write a new one anytime, anywhere. It is more convenient to keep copying and pasting to change part of the material for mass production items. Text editor can save time in the editor and button interaction to do more things

**Comment by HansOffice** [comment]
The text editor is indeed much faster than the graphical editor, which saves a lot of time by removing the time spent on button interaction.

**Comment by knokko** [comment]
I don't see why you would copy many attributes between items: aren't all your items supposed to be unique? (And if you do need to copy them, there is this `Copy` button that serves this purpose.)

And what would you want me to do? Dump all your textures, items, recipes, container, and projectiles in 1 massive text file that you can edit with a text editor?

**Comment by HansOffice** [comment]
My idea is to make the material inside can be called at any time, for example, there is a diamond sword written in the text, then I can call inside Custom items inside the sword material to override the diamond sword to make the diamond sword into the material I call

**Comment by HansOffice** [comment]
And the game can also call his material at any time, instead of writing in the editor to reload once to make its face change, in line with lore properties plug-in at the same time this will make the plug-in has a higher degree of freedom

**Comment by knokko** [comment]
I'm sorry, but I don't understand your last 3 messages. In particular, I'm not sure what you mean by **call**. And what exactly do you mean by **material**? Diamond? Some custom item?

**Comment by HansOffice** [comment]
I just want him to be able to quickly edit weapons in the text editor and then can directly call the corresponding item material in it, is completely independent to write the kind of (equivalent to give an example and then the following can refer to that example to write the item) so I personally think the efficiency will be easier and faster than gui interaction

**Comment by knokko** [comment]
Ok. You are not the first one who requested text-based editing, so I might implement it someday. However, it will be lots of work for only efficiency improvements, so it won't happen anytime soon.

**Comment by HansOffice** [comment]
Okay, I have understood, cheers 7W7
