### ISSUE TITLE
Full geyser support?

### ISSUE THREAD

**Issue by knokko** [knokko/custom-items-gradle#193]
Currently, Geyser support is very limited: Bedrock players can't see any textures. It might be possible to add full (or just more) support. This documentation might help: https://github.com/GeyserCustomModelData/HowTo
If not, their Discord server might provide some help.

**Comment by BobtheBob123456** [comment]
Whole currently, Geyser is working towards adding Bedrock custom model data (and have reached some success) they have still not added support for blocks.

**Comment by knokko** [comment]
Interesting... if this issue would be solved entirely on the Geyser side, I might not even need to do anything myself (or at least do less work).

**Comment by BobtheBob123456** [comment]
Here is how.

1. Download and install this version of geyser on your server (https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252Fextensions/)
2. Get a direct download link for your java resource pack
3. Go to this converter, and open an issue to convert your pack (https://github.com/Kas-tle/java2bedrock.sh/actions)
4. Once your pack is converted, go to the action run, and get your pack
5. From the .zip archive take the geyser_resources.mcpack and the custom_mappings.json 
6. Put the .mcpack in the packs folder and the .json I the custom mappings folder
7. Let bedrock players join and download your pack

Note: If something is wrong with the bedrock pack, check the action run log to see what went wrong.

To see the status of the project and upcoming updates, check here (https://github.com/GeyserMC/Geyser/issues/210). If you want to see an example of a converted pack, check here (https://www.dropbox.com/s/0n0o0ax110382qj/Archive.zip?dl=1).

**Comment by knokko** [comment]
KCI 13 will have reasonable Geyser support, but it won't be complete because that's very hard/impossible.
