### ISSUE TITLE
The material of the original bow is lost

### ISSUE THREAD

**Issue by HansOffice** [knokko/custom-items-gradle#194]
I made a bow with other materials and imported it to display normally, but the original bow material is lost
Has been tested is the problem of the material package, do not open the material package on the problem
![2022-08-10_22 17 04](https://user-images.githubusercontent.com/94523696/183924578-b40af67e-a35d-4af7-8ac3-75654b13449f.png)
.

**Comment by knokko** [comment]
This will be fixed in Editor 10.10, which I will probably release within a week.

**Comment by knokko** [comment]
Editor 10.10 has been released
