### ISSUE TITLE
On Mac it crashes when i try to load a texture or do many things

### ISSUE THREAD

**Issue by ashtli10** [knokko/custom-items-gradle#219]
Idk what hapens i cant use it on mac everithyng crashes. pls help

**Comment by knokko** [comment]
That's quite weird. Although I have never tested this on a mac, I heard from other people that it worked. Could you show the latest 2 files in `home/Custom Item Sets/logs/`? (One of them should start with `err` and the other should start with `out`. One of them should tell the reason why it's crashing.)

**Comment by ashtli10** [comment]
[out 1674138646103.txt](https://github.com/knokko/custom-items-gradle/files/10459850/out.1674138646103.txt)
[out 1674152041276.txt](https://github.com/knokko/custom-items-gradle/files/10459851/out.1674152041276.txt)
there? is that it

**Comment by ashtli10** [comment]
[err 1668373759979.txt](https://github.com/knokko/custom-items-gradle/files/10459855/err.1668373759979.txt)
[err 1668373984393.txt](https://github.com/knokko/custom-items-gradle/files/10459857/err.1668373984393.txt)
[err 1674089575816.txt](https://github.com/knokko/custom-items-gradle/files/10459858/err.1674089575816.txt)
[err 1674090473636.txt](https://github.com/knokko/custom-items-gradle/files/10459859/err.1674090473636.txt)
[err 1674090521801.txt](https://github.com/knokko/custom-items-gradle/files/10459860/err.1674090521801.txt)
[err 1674137001635.txt](https://github.com/knokko/custom-items-gradle/files/10459861/err.1674137001635.txt)
[err 1674137058798.txt](https://github.com/knokko/custom-items-gradle/files/10459862/err.1674137058798.txt)
[err 1674137206313.txt](https://github.com/knokko/custom-items-gradle/files/10459863/err.1674137206313.txt)
[err 1674137967373.txt](https://github.com/knokko/custom-items-gradle/files/10459864/err.1674137967373.txt)
[err 1674138646103.txt](https://github.com/knokko/custom-items-gradle/files/10459865/err.1674138646103.txt)
[err 1674152041276.txt](https://github.com/knokko/custom-items-gradle/files/10459867/err.1674152041276.txt)
[out 1668373759979.txt](https://github.com/knokko/custom-items-gradle/files/10459868/out.1668373759979.txt)
[out 1668373984393.txt](https://github.com/knokko/custom-items-gradle/files/10459869/out.1668373984393.txt)
[out 1674089575816.txt](https://github.com/knokko/custom-items-gradle/files/10459870/out.1674089575816.txt)
[out 1674090473636.txt](https://github.com/knokko/custom-items-gradle/files/10459871/out.1674090473636.txt)
[out 1674090521801.txt](https://github.com/knokko/custom-items-gradle/files/10459872/out.1674090521801.txt)
[out 1674137001635.txt](https://github.com/knokko/custom-items-gradle/files/10459874/out.1674137001635.txt)
[out 1674137058798.txt](https://github.com/knokko/custom-items-gradle/files/10459875/out.1674137058798.txt)
[out 1674137206313.txt](https://github.com/knokko/custom-items-gradle/files/10459876/out.1674137206313.txt)
[out 1674137967373.txt](https://github.com/knokko/custom-items-gradle/files/10459877/out.1674137967373.txt)
[out 1674138646103.txt](https://github.com/knokko/custom-items-gradle/files/10459878/out.1674138646103.txt)
[out 1674152041276.txt](https://github.com/knokko/custom-items-gradle/files/10459879/out.1674152041276.txt)
here are all of them

**Comment by knokko** [comment]
Hm... I can't find any errors in any of them. Could you delete all files in the `logs`, run the Editor again, intentionally do something that makes it crash, and send the 2 new log files?

**Comment by ashtli10** [comment]
[err 1674152502465.txt](https://github.com/knokko/custom-items-gradle/files/10459934/err.1674152502465.txt)
[out 1674152502465.txt](https://github.com/knokko/custom-items-gradle/files/10459935/out.1674152502465.txt)

**Comment by knokko** [comment]
Unfortunately, neither of these files contain any errors (perhaps it crashes before it can finish the logs). I know 1 other way to find errors, but it's a bit more complicated:
- Go to the directory that contains `Editor.jar`
- Open a terminal in that directory (or maybe something like git bash, I'm not sure what options macs have). You can hopefully do this by right-clicking that directory in your file browser and choose something like `Open in terminal`.
- Run `java -jar Editor.jar` in that terminal.
- Do something that makes it crash
- Hopefully, this spits out some error, which can you copy & paste here.

**Comment by ashtli10** [comment]
idk how to get top the directory of the file its in documents

**Comment by knokko** [comment]
Perhaps you can instead open it in a subdirectory of documents? Then you should run `cd ..` before doing `java -jar Editor.jar`.

**Comment by ashtli10** [comment]
java -jar Editor.jar 
Error: Unable to access jarfile Editor.jar

**Comment by knokko** [comment]
Is `Editor.jar` listed when you run `ls`?

**Comment by ashtli10** [comment]
no

**Comment by ashtli10** [comment]
THERE i got somthing

**Comment by ashtli10** [comment]
i did the command it opened and i crashed it and it sent this


asthli@Ariels-MacBook-Pro Documents % java -jar Editor.jar
test out
test error
All system tests succeeded
2023-01-19 12:43:23.590 java[47944:3091985] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80e4377c3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80e197bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80e460076 -[NSException raise] + 9
	3   AppKit                              0x00007ff810e1c0a4 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff810e08054 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1288
	5   AppKit                              0x00007ff810fb0d81 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	6   AppKit                              0x00007ff810e07b46 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	7   AppKit                              0x00007ff810fb0d3a -[NSPanel initWithContentRect:styleMask:backing:defer:] + 59
	8   AppKit                              0x00007ff8117fcf16 -[NSSavePanel initWithContentRect:styleMask:backing:defer:] + 91
	9   AppKit                              0x00007ff811806b7b -[NSOpenPanel initWithContentRect:styleMask:backing:defer:] + 150
	10  AppKit                              0x00007ff8110ed078 -[NSPanel init] + 69
	11  AppKit                              0x00007ff8117fce98 -[NSSavePanel init] + 197
	12  AppKit                              0x00007ff8114c48a2 +[NSSavePanel(Instantiation) _crunchyRawUnbonedPanel] + 58
	13  liblwjgl_nfd.dylib                  0x000000011f1e5582 liblwjgl_nfd.dylib + 5506
	14  ???                                 0x0000000108dfc747 0x0 + 4443850567
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      java -jar Editor.jar

**Comment by knokko** [comment]
That is almost certainly the problem I was looking for. I will try to fix it

**Comment by ashtli10** [comment]
ok thank you alot bye

**Comment by knokko** [comment]
Maybe a couple of hours, maybe a couple of days. It's hard to make accurate predictions about bugfixing

**Comment by ashtli10** [comment]
ok i hope its soon tell me when

**Comment by knokko** [comment]
I created a new version of the Editor that may or may not fix the crash. I would like you to try it out!
You can find it at https://knokko.github.io/resourcedumps/EditorMac.jar
Could you run this version via `java -jar EditorMac.jar`? Note: I only updated the file picker at this page: https://knokko.github.io/custom%20items/editor%20documentation/edit%20menu/textures/edit.html All other file pickers are still broken (I will fix them once you confirm that the texture picker works.)
You can access this page via Open Editor -> Edit item set/new item set -> Textures -> Load texture

**Comment by ashtli10** [comment]
it dont open

**Comment by ashtli10** [comment]
<img width="120" alt="Screen Shot 2023-01-20 at 11 28 52 AM" src="https://user-images.githubusercontent.com/69227962/213764846-04b1de3e-111a-4c8c-8981-013de6589ae4.png">
it says editor but its nothing on my scvreen

**Comment by knokko** [comment]
Could you forcibly terminate the Editor 'window' (the one that doesn't want to open), but while keeping the terminal open? I'm curious what it will spit out

**Comment by knokko** [comment]
I also made this custom version that you could try: https://knokko.github.io/resourcedumps/EditorMac2.jar
And how about Editor 11.3? https://dev.bukkit.org/projects/custom-items-and-textures/files/4056499 (This was the last version before I switched the file picker)

**Comment by ashtli10** [comment]
Last login: Fri Jan 20 12:56:42 on ttys000
asthli@Ariels-MacBook-Pro ~ % cd downloads
asthli@Ariels-MacBook-Pro downloads % java -jar EditorMac2.jar
test out
test error
All system tests succeeded
Entering main thread task loop...
test1
2023-01-21 10:17:17.071 java[6414:326381] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff811ed87c3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff811c38bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff811f01076 -[NSException raise] + 9
	3   AppKit                              0x00007ff8148bd0a4 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff8148a9054 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1288
	5   AppKit                              0x00007ff814a51d81 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	6   AppKit                              0x00007ff8148a8b46 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	7   AppKit                              0x00007ff814a51d3a -[NSPanel initWithContentRect:styleMask:backing:defer:] + 59
	8   AppKit                              0x00007ff81529df16 -[NSSavePanel initWithContentRect:styleMask:backing:defer:] + 91
	9   AppKit                              0x00007ff8152a7b7b -[NSOpenPanel initWithContentRect:styleMask:backing:defer:] + 150
	10  AppKit                              0x00007ff814b8e078 -[NSPanel init] + 69
	11  AppKit                              0x00007ff81529de98 -[NSSavePanel init] + 197
	12  AppKit                              0x00007ff814f658a2 +[NSSavePanel(Instantiation) _crunchyRawUnbonedPanel] + 58
	13  liblwjgl_nfd.dylib                  0x00000001212cf582 liblwjgl_nfd.dylib + 5506
	14  ???                                 0x000000010f8b6747 0x0 + 4555761479
	15  ???                                 0x000000010f8a5d80 0x0 + 4555693440
	16  ???                                 0x000000010f8a5d80 0x0 + 4555693440
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      java -jar EditorMac2.jar

**Comment by ashtli10** [comment]
HEY it WORKED
downloads % java -jar Editor.jar     
test out
test error
All system tests succeeded
and i could search for texturwes with the latest bukkit one

**Comment by knokko** [comment]
Thanks for reporting this problem and helping me debug. I just published Editor 11.7, which should use this old file picker when it's running on MacOS.
