### ISSUE TITLE
Is there any way without optifine other people can see the custom armor from the outside

### ISSUE THREAD

**Issue by ashtli10** [knokko/custom-items-gradle#221]
I always see texture packs that show iron armor custom knight and stuff so I was wondering if there's a way to do that cause from the outside it just looks like diamond armor?

**Comment by knokko** [comment]
Not really: vanilla minecraft doesn't really support custom armor. The best thing you use for now is colored leather armor. In a later version, Fancy Pants might be able to do the trick, but I haven't explored it yet: https://github.com/knokko/custom-items-gradle/issues/188

**Comment by knokko** [comment]
This will be implemented in #188
