### ISSUE TITLE
Is there a way to get custom items to appear on DeluxeMenus?

### ISSUE THREAD

**Issue by HansOffice** [knokko/custom-items-gradle#248]
I want my finished custom items to appear on the menu buttons made by the DeluxeMenus plugin, is there any way to do that? Or is this supported?

**Comment by knokko** [comment]
Putting `KnokkosCustomItems: { Name: "name_of_your_item" }` in the NBT of an item will turn it into a custom item. If the DeluxeMenu config supports NBT, this should do the trick (I don't know DeluxeMenu, so I don't know whether it does). If not, this will be more difficult.

**Comment by HansOffice** [comment]
> 放入`KnokkosCustomItems: { Name: "name_of_your_item" }`一件物品的NBT会将其变成一件自定义物品。如果 DeluxeMenu 配置支持 NBT，这应该可以解决问题（我不知道 DeluxeMenu，所以我不知道它是否支持）。如果没有，这将更加困难。

I see that he supports nbt tag, but his example I do not understand how to write
![QQ图片20230605021150](https://github.com/knokko/custom-items-gradle/assets/94523696/010953b7-28b1-4286-aee9-f7d9009d7928)

**Comment by knokko** [comment]
I'm not sure whether it supports nested strings (which you will need). I think you should contact the support/dev of DeluxeMenu

**Comment by HansOffice** [comment]
> 我不确定它是否支持嵌套字符串（您将需要）。我认为您应该联系 DeluxeMenu 的支持/开发人员
Okay, thanks for the reply

**Comment by knokko** [comment]
Did you get an answer?

**Comment by HansOffice** [comment]
> Did you get an answer?

No, I didn't get any answer, I tried to change to another menu plugin but it didn't seem to work either, I chose to give up the struggle
