### ISSUE TITLE
Add custom armor bonusses when wearing specific other custom armor pieces as well

### ISSUE THREAD

**Issue by knokko** [knokko/custom-items-gradle#54]
Currently, custom armor (and all other custom items) can have attribute modifiers. But, these are always the same. It could be interesting to improve these attribute modifiers if the player also equips a related armor piece (but in a different slot).

Simple example: an emerald chestplate should add 8.0 armor if worn without emerald leggings, but should add 9.0 armor if the player also wears emerald leggings (and for instance 10.0 armor if the player wears emerald helmet or boots as well...)

Add similar possibilities for damage resistances and potion effects.

**Comment by Phoenixvine32908** [comment]
That would be so cool
