### ISSUE TITLE
Removing armor textures

### ISSUE THREAD

**Issue by knokko** [knokko/custom-items-gradle#63]
Someone noticed that it is currently impossible to remove worn armor textures. Trying to do so results in the following error:
[err 1613121059032.txt](https://github.com/knokko/custom-items-gradle/files/5970702/err.1613121059032.txt)

**Comment by TechWizzart** [comment]
Had another report with the following log [err_1613127083044.txt](https://github.com/knokko/custom-items-gradle/files/5971382/err_1613127083044.txt), relating to deleting items. Perhaps the delete button itself is broken and not only the delete button in the textures section.

**Comment by knokko** [comment]
I made a separate issue for the error you just mentioned. Judging by the stacktraces, they are different errors. Besides, the item deletion only malfunctions in certain circumstances. Deleting armor textures always malfunctions.

**Comment by knokko** [comment]
This will be solved in Editor 8.5
